name: deployment

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "application/packages/deno/**"
      - "application/packages/nest/**"
      - "application/packages/node/**"
      - "application/packages/common/**"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: application
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm install
      - run: npm run format
      - run: npm run test
      - run: npm run build
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN  }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
